# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
arr[8]

8

In [7]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Setting a value with index range (Broadcasting)
arr[0:4]=0

#Show
arr

array([ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [18]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [22]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
#Indexing row
arr_2d[2]


array([ 5, 10, 15])

In [23]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [25]:
# Getting individual element value
arr_2d[2,1]

40

In [27]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [29]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [41]:
arr_3d = np.random.randn(27)
arr_3d

array([-0.6526091 , -0.02630934,  0.91983003,  0.15993554, -1.07591101,
       -0.75905247, -0.07146194, -0.08286636,  0.03489129, -1.15258972,
        1.28084973, -2.06809008, -0.77435655,  1.61441021,  0.35558346,
       -0.08483462, -0.58064828,  0.0640257 ,  1.80586206, -0.04544015,
       -0.66970155,  0.13441481, -1.25054461, -1.04630676, -2.52055913,
        0.3202927 ,  0.36638039])

In [37]:
arr_3d_1 = arr_3d.reshape(3,3,3)

In [38]:
arr_3d_1

array([[[[ 5.96403995e-01, -1.15465189e+00,  5.33008217e-02,
           1.44021430e-01],
         [ 4.49581017e-01,  1.99967188e-01,  3.10924068e+00,
           3.13873747e-01],
         [-3.04654826e-01,  7.70615345e-01,  8.40151146e-01,
          -1.20726234e+00],
         [-1.32588391e+00, -9.10082726e-01, -1.80050721e-02,
           4.25825066e-01]],

        [[-1.78037619e-01, -1.01061752e+00,  1.25714994e-01,
          -9.61068189e-02],
         [ 8.06725390e-01,  4.84974313e-01, -8.84193526e-01,
          -9.21551791e-01],
         [ 3.90584010e-01,  1.14418725e+00, -1.57229670e-01,
           8.65170262e-02],
         [-1.31528501e+00, -6.51399104e-01,  1.95786907e-01,
          -1.89628826e+00]],

        [[ 7.88259673e-03,  1.56744637e+00,  2.06417733e+00,
           3.92678401e-01],
         [-3.48436500e-01, -8.97203846e-01, -6.69150181e-01,
           8.19061768e-02],
         [-6.04994547e-01, -3.50770159e-01,  1.09739642e+00,
           1.35154086e+00],
         [-1.7557

In [40]:
arr_3d_1[2,3,2,1:]

array([0.30242856, 1.20761632, 0.99585022])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [51]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [53]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [56]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [57]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [58]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
bool_arr = arr>4

In [61]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])