In [ ]:
ML Libraries-> Numpy ->Numerical Python  , Pandas->Dataset, Matplotlib Seaborn - Data Visualization,Sklearn->ML algorithms 
Scipy->Scientific Python->Statistics

NumPy is a Linear Algebra Library for Python. all libraries us numpy as a base for building other libraries.
Numpy is also very fast

## Numpy Tutorial

Import numpy as a library. np is a general convention

In [1]:
import numpy as np

# Numpy
Numpy: Vectors,Arrays,Matrices, and Random Number Generation.


Numpy arrays essentially come in two types: Vectors and Matrices. 
Vectors are strictly 1-d arrays
Matrices are 2-d 
Numpy arrays are a list or list of lists:

In [2]:
list1 = [5,6,7]
list1

[5, 6, 7]

In [3]:
np.array(list1)

array([5, 6, 7])

In [4]:
matrix1 = [[0,1,2],[3,4,5],[6,7,8]]
matrix1

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [5]:
np.array(matrix1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(100,4,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8])

Zeros and Ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
a=np.zeros(6,int)
a

array([0, 0, 0, 0, 0, 0])

In [17]:
a = np.zeros((6,6),int)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3,3),int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

Return numbers in a range or over a specified interval. default for num is given as 50. Change paramenters to see how it is generated. 

In [20]:
np.linspace(0,45,15) #linearly spaced

array([ 0.        ,  3.21428571,  6.42857143,  9.64285714, 12.85714286,
       16.07142857, 19.28571429, 22.5       , 25.71428571, 28.92857143,
       32.14285714, 35.35714286, 38.57142857, 41.78571429, 45.        ])

## np.linspace(0,10,50).astype(int)

In [22]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])


Create an identity matrix or an I matrix

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random numbers

Numpy also has several ways to create random number arrays:


In [28]:
np.random.rand(20) # generates values between 0 and 1

array([0.738359  , 0.50732303, 0.24106275, 0.72084748, 0.00919007,
       0.61158581, 0.25435373, 0.64563043, 0.46129702, 0.98450329,
       0.09911723, 0.26709422, 0.95522457, 0.25381332, 0.66400104,
       0.87495593, 0.94813669, 0.57954724, 0.92440322, 0.72763378])

In [29]:
A = np.random.rand(5,5)
A

array([[0.76083092, 0.20558529, 0.45565146, 0.50531915, 0.39010006],
       [0.35660231, 0.12899268, 0.29165547, 0.90872394, 0.46463144],
       [0.88502555, 0.76595711, 0.03123437, 0.42857893, 0.75811478],
       [0.24637072, 0.65990954, 0.07382374, 0.5607964 , 0.19202444],
       [0.14605402, 0.45627323, 0.03933049, 0.38191807, 0.46966897]])

In [31]:
sigma, mean = 3, 15

In [32]:
B = sigma*A + mean

B

array([[17.28249275, 15.61675586, 16.36695438, 16.51595745, 16.17030019],
       [16.06980693, 15.38697805, 15.87496641, 17.72617183, 16.39389431],
       [17.65507664, 17.29787132, 15.09370311, 16.28573679, 17.27434434],
       [15.73911216, 16.97972862, 15.22147121, 16.68238919, 15.57607332],
       [15.43816206, 16.36881969, 15.11799146, 16.14575422, 16.40900692]])

### Below: Return samples from the "standard normal" distribution. Rand function is a uniform distribution. For ex: you will get approximately 20% of the values between 0 and 0.2. 

In [33]:
np.random.randn(25)

array([ 0.80193555, -0.99044116,  0.20721113, -0.16423445, -2.37339598,
        1.45518548,  0.10815002,  1.55147274, -1.39448805, -0.93543946,
        0.25675012,  0.67071981,  1.53704585, -0.89482979, -0.67400673,
        0.16495702,  0.2221953 , -0.32154918, -0.0456619 , -0.29850173,
       -2.02727009, -0.09732867, -0.32714149,  0.36464566, -0.08587011])

In [34]:
np.random.randn(5,5)

array([[-0.46116317,  0.57135908, -0.37694603, -0.37457161, -1.07070027],
       [-0.38018239, -1.68545403, -0.53544913, -1.03927956,  0.24350527],
       [ 0.1453782 , -0.07112208, -1.68280447, -1.08927372,  0.43149341],
       [ 1.42575297,  1.00156893,  0.04671457,  0.94231612, -1.16720159],
       [ 0.95047702,  0.46103756,  0.43957426, -1.00815826,  0.66124708]])

randint
Return random integers from low to high (inclusive).

In [44]:
np.random.randint(1,3)

2

In [36]:
np.random.randint(1,10,100)

array([9, 7, 2, 3, 2, 7, 1, 3, 3, 1, 2, 6, 3, 4, 2, 3, 8, 4, 4, 3, 9, 9,
       3, 1, 3, 7, 1, 6, 7, 4, 9, 8, 3, 8, 1, 8, 9, 1, 8, 6, 5, 6, 6, 4,
       7, 2, 6, 8, 3, 7, 4, 3, 9, 7, 7, 2, 9, 3, 3, 3, 1, 5, 6, 8, 4, 3,
       2, 2, 2, 6, 9, 8, 5, 6, 5, 9, 2, 7, 6, 1, 9, 6, 7, 7, 6, 4, 5, 6,
       4, 4, 9, 1, 6, 3, 3, 1, 2, 3, 1, 2])

In [45]:
np.random.randint(10,1,100)

ValueError: low >= high


Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [46]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr

array([40, 21, 31, 31,  2, 49, 32,  0,  0, 28])

## Reshape
Returns an array containing the same data with a new shape.

In [49]:
arr1 = arr.reshape(5,5)

In [50]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.reshape(2,5)

ValueError: cannot reshape array of size 25 into shape (2,5)

max,min,argmin,argmax

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [52]:
ranarr

array([40, 21, 31, 31,  2, 49, 32,  0,  0, 28])

In [53]:
ranarr[0]=49

In [54]:
ranarr

array([49, 21, 31, 31,  2, 49, 32,  0,  0, 28])

In [55]:
ranarr.max()

49

In [57]:
ranarr.argmax()

0

In [56]:
ranarr.min()

0

In [58]:
ranarr.argmin()

7

In [59]:
ranarr.mean()

24.3

In [61]:
ranarr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

## Shape

Shape is an attribute that arrays have (not a method):

In [66]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
# Vector
arr.shape

(25,)

In [68]:
# Notice the two sets of brackets
arr1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
arr.reshape(1,25).shape

(1, 25)

In [69]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [70]:
arr.reshape(25,1).shape
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### dtype

You can also grab the data type of the object in the array:

In [71]:
A

array([[0.76083092, 0.20558529, 0.45565146, 0.50531915, 0.39010006],
       [0.35660231, 0.12899268, 0.29165547, 0.90872394, 0.46463144],
       [0.88502555, 0.76595711, 0.03123437, 0.42857893, 0.75811478],
       [0.24637072, 0.65990954, 0.07382374, 0.5607964 , 0.19202444],
       [0.14605402, 0.45627323, 0.03933049, 0.38191807, 0.46966897]])

In [72]:
A.dtype

dtype('float64')

In [73]:
n_array = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])


In [74]:
res = np.where(n_array == 0)[0]
print(res)

[ 1  3  5  6 11]


Syntax:

numpy.where(condition[, x, y])

When True, yield x, otherwise yield y

In [75]:
A = np.array([[1,2,3],[2,3,4],[3,4,5]]) # Initialize matrix

In [76]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [79]:
B = np.array([[2,3,4],[3,4,5],[4,5,6]]) # Initialize another matrix

In [80]:
B

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [187]:
C = A+B # Matrix Addition/Subtraction
C

array([[ 3,  5,  7],
       [ 5,  7,  9],
       [ 7,  9, 11]])

In [188]:
C = A*B #
C 

array([[ 2,  6, 12],
       [ 6, 12, 20],
       [12, 20, 30]])

In [77]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [81]:
B

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [189]:
C = np.dot(A,B)
C

array([[20, 26, 32],
       [29, 38, 47],
       [38, 50, 62]])

In [82]:
A_1 = np.array([[1,2,3],[2,3,4]])
B_1 = np.array([[2,3],[3,4],[4,5]])

In [83]:
A_1

array([[1, 2, 3],
       [2, 3, 4]])

In [84]:
B_1

array([[2, 3],
       [3, 4],
       [4, 5]])

In [191]:
C_1 = np.dot(A_1,B_1)
C_1

array([[20, 26],
       [29, 38]])

In [198]:
import numpy as np



In [202]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_id

array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [203]:
i = np.argsort(student_id)
i

array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [204]:
print(i[2])

4


### For more on Linear Algebra related functions. visit the following link

https://numpy.org/doc/stable/reference/routines.linalg.html

## Numpy operations

In [85]:
arr=np.arange(1,10)

In [86]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [89]:
arr/1

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [91]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [92]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [94]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [95]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [97]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

### Indexing and slicing

In [100]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr[0]

1

In [102]:
arr[8]

9

In [103]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 9

In [104]:
arr[0:4]

array([1, 2, 3, 4])

In [105]:
arr[2:6]

array([3, 4, 5, 6])

In [106]:
arr[2:4]=0

In [107]:
arr

array([1, 2, 0, 0, 5, 6, 7, 8, 9])

In [108]:
arr_copy=arr.copy()
arr_copy

array([1, 2, 0, 0, 5, 6, 7, 8, 9])

In [110]:
arr2=np.array([[2,4,6],[10,13,24],[25,76,12]])
arr2

array([[ 2,  4,  6],
       [10, 13, 24],
       [25, 76, 12]])

In [112]:
arr2[1]

array([10, 13, 24])

In [113]:
arr2[0,2]

6

In [114]:
arr2[0:2,1:3]

array([[ 4,  6],
       [13, 24]])

In [116]:
arr2[2][1:3]

array([76, 12])